apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-backend
  template:
    metadata:
      labels:
        app: inventory-backend
    spec:
      containers:
      - name: backend
        image: ahmed7amed9/inventory-backend:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@postgres-service:5432/inventory
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: inventory-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30007
