apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-frontend
  template:
    metadata:
      labels:
        app: inventory-frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: inventory-frontend
  ports:
  - port: 80
    targetPort: 80
