apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-gateway
  template:
    metadata:
      labels:
        app: inventory-gateway
    spec:
      containers:
      - name: gateway
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: inventory-gateway
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
